### ISSUE TITLE
Need to update node version for app in docker compose file

### ISSUE THREAD

**Issue by bmcdonn2** [chirpradio/nextup#96]
As it stands now, trying to run the app locally will generate the following error when trying to interact with the datastore:

```
app  | Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
app  |     at GoogleAuth.getApplicationDefaultAsync (/usr/src/app/node_modules/google-auth-library/build/src/auth/googleauth.js:183:19)
app  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
app  |     at async GoogleAuth.getClient (/usr/src/app/node_modules/google-auth-library/build/src/auth/googleauth.js:565:17)
app  |     at async GrpcClient._getCredentials (/usr/src/app/node_modules/@google-cloud/datastore/node_modules/google-gax/build/src/grpc.js:145:24)
app  |     at async GrpcClient.createStub (/usr/src/app/node_modules/@google-cloud/datastore/node_modules/google-gax/build/src/grpc.js:308:23)

```

I found that updating this line to node v20.11.0 resolves the issue:

https://github.com/chirpradio/nextup/blob/373cf2928bb4385efe4ae62b79320a7cd1fa52b4/docker-compose.yml#L6

I could go ahead and handle this one but I wasn't sure if the change might be pending in a different branch. Let me know.

**Comment by lund5000** [comment]
I thought I had made this change already, so go ahead and pop in a quick PR for it 👍
